//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class usc
    {
        public int scid { get; set; }
        public string sid { get; set; }
        public string cid { get; set; }
        public string term { get; set; }
        public string score1 { get; set; }
        public string score2 { get; set; }
        public string score3 { get; set; }
        public string score { get; set; }
    }
}
