//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class uteacher
    {
        public int tid { get; set; }
        public string tname { get; set; }
        public string tsexy { get; set; }
        public string tbdate { get; set; }
        public string tfield { get; set; }
        public string tprof { get; set; }
        public string tele { get; set; }
        public string qq { get; set; }
        public string email { get; set; }
        public string msn { get; set; }
        public string did { get; set; }
    }
}
