//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ujobtable
    {
        public int jid { get; set; }
        public string cid { get; set; }
        public string room { get; set; }
        public string tid { get; set; }
        public string week { get; set; }
        public string timeseg { get; set; }
        public string gid { get; set; }
        public string term { get; set; }
    }
}
