//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ustudent
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public string ssexy { get; set; }
        public string sbdate { get; set; }
        public string gid { get; set; }
        public string stele { get; set; }
    }
}
