//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class udept
    {
        public int dept_id { get; set; }
        public string acronym { get; set; }
        public string dname { get; set; }
        public string daddr { get; set; }
        public string dtele { get; set; }
        public string demail { get; set; }
    }
}
