//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_enterprise
    {
        public int id { get; set; }
        public Nullable<int> annual_value { get; set; }
        public string city_code { get; set; }
        public Nullable<int> city_id { get; set; }
        public string city_name { get; set; }
        public string county_code { get; set; }
        public Nullable<int> county_id { get; set; }
        public string county_name { get; set; }
        public string detail_address { get; set; }
        public string economy_name { get; set; }
        public Nullable<int> economy_type { get; set; }
        public Nullable<int> employee_number { get; set; }
        public string enterprise_name { get; set; }
        public Nullable<System.DateTime> establish_time { get; set; }
        public Nullable<double> factory_area { get; set; }
        public Nullable<System.DateTime> gmt_create { get; set; }
        public Nullable<System.DateTime> gmt_modified { get; set; }
        public string industry_name { get; set; }
        public Nullable<int> industry_type { get; set; }
        public Nullable<int> is_delete { get; set; }
        public Nullable<int> latitude { get; set; }
        public string legal_person { get; set; }
        public Nullable<int> longitude { get; set; }
        public string main_industry { get; set; }
        public string operat_product { get; set; }
        public string pluralistic_management { get; set; }
        public string province_code { get; set; }
        public Nullable<int> province_id { get; set; }
        public string province_name { get; set; }
        public string safe_charge { get; set; }
        public string safe_management { get; set; }
        public string street_code { get; set; }
        public Nullable<int> street_id { get; set; }
        public string street_name { get; set; }
        public string village_code { get; set; }
    }
}
