//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucourse
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public string credit { get; set; }
        public string pcid { get; set; }
        public string chour { get; set; }
        public string cattr { get; set; }
        public string cnum { get; set; }
        public string did { get; set; }
    }
}
